name: ecommerce_int2
description: It is about a complete ecommerce app for Android and iOS. 

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5  
  card_swiper: ^3.0.1
  flutter_staggered_grid_view: ^0.7.0
  rubber: ^1.0.1
  pin_code_text_field: ^1.8.0
  http: ^1.5.0
  flutter_rating_bar: ^4.0.0
  intl: ^0.20.2
  numberpicker: ^2.1.2
  flutter_svg: ^2.0.2
  cached_network_image: ^3.4.1
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.2.2
  encrypt: ^5.0.1
  email_validator: ^3.0.0
  synchronized: ^3.1.0
  flutter_local_notifications: ^19.5.0
  workmanager: ^0.9.0
  connectivity_plus: ^6.1.0
  shimmer: ^3.0.0
  hive_flutter: ^1.1.0
  
  # Firebase for instant push notifications
  firebase_core: ^4.2.1
  firebase_messaging: ^16.0.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  build_runner: ^2.4.11
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  mocktail: ^1.0.4
  hive_generator: ^2.0.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/shopeLogo.png"


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
  - assets/
  - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  # - family: Montserrat
  #   fonts:
  #   - asset: fonts/Montserrat-Regular.ttf
  # - family: NunitoSans
  #   fonts:
  #   - asset: fonts/NunitoSans-Regular.ttf

